run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - misspell
    - unconvert
    - ineffassign
    - copyloopvar

linters-settings:
  staticcheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1020", "-ST1016"]
  errcheck:
    exclude-functions:
      - (*encoding/json.Encoder).Encode

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
