# Used by goreleaser: ships pre-built binaries instead of building from source.
FROM gcr.io/distroless/static-debian12:nonroot

WORKDIR /app
COPY omniswitch /usr/local/bin/omniswitch
COPY policies ./policies
COPY examples ./examples

EXPOSE 8080
ENV OMNISWITCH_LISTEN=:8080
ENV OMNISWITCH_DATA=/data

ENTRYPOINT ["/usr/local/bin/omniswitch"]
