apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omniswitch.fullname" . }}-config
  labels:
    {{- include "omniswitch.labels" . | nindent 4 }}
data:
  gateway.yaml: |
{{ toYaml .Values.config | indent 4 }}
