apiVersion: v1
kind: Service
metadata:
  name: omniswitch-gateway
  namespace: omniswitch
  labels:
    app.kubernetes.io/name: omniswitch
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: omniswitch
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: 8080
      targetPort: http
